stages:
  - build
  - test
  - publish
  - deploy

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

variables:
  DOCKER_REGISTRY: 043953693619.dkr.ecr.us-east-1.amazonaws.com
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build:
  image: gradle:jdk11
  stage: build
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - gradle wrapper
  script:
    - ./gradlew --build-cache assemble
  artifacts:
    paths:
    - e-auction-command-api/build/libs/e-auction-command-api-1.0.0.jar
    - e-auction-query-api/build/libs/e-auction-query-api-1.0.0.jar
    expire_in: 1 hour

test:
  stage: test
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - gradle wrapper
  script:
    - ./gradlew --build-cache check
    - ./gradlew --build-cache test jacocoTestReport
  artifacts:
    when: always
    reports:
      junit: ./**/build/test-results/test/TEST-*.xml
    paths:
      - ./**/build/jacoco/test/html

publish:
  stage: publish
  image: docker:20.10.12
  services:
    - name: docker:20.10.12-dind
  before_script:
    - apk add --no-cache curl jq python3 py3-pip
    - pip install awscli
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
  script:
    - cd e-auction-query-api
    - docker build -t $DOCKER_REGISTRY/e-auction-query-api:$CI_PIPELINE_IID -t $DOCKER_REGISTRY/e-auction-query-api:latest .
    - docker push --all-tags $DOCKER_REGISTRY/e-auction-query-api
    - cd ../e-auction-command-api
    - docker build -t $DOCKER_REGISTRY/e-auction-command-api:$CI_PIPELINE_IID -t $DOCKER_REGISTRY/e-auction-command-api:latest .
    - docker push --all-tags $DOCKER_REGISTRY/e-auction-command-api
  only:
  - main

deploy:eb:
  stage: deploy
  image: python:latest
  before_script:
    - pip install awsebcli --upgrade --user
  script:
    - mkdir ~/.aws/
    - touch ~/.aws/credentials
    - printf "[eb-cli]\naws_access_key_id = %s\naws_secret_access_key = %s\n" "$AWS_ACCESS_KEY_ID" "$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
    - touch ~/.aws/config
    - printf "[profile eb-cli]\nregion=us-east-1\noutput=json" >> ~/.aws/config
    - ~/.local/bin/eb deploy e-auction-command-api
  only:
  - main

deploy:ecs:
  stage: deploy
  image: python:latest
  before_script:
    - pip install awscli
  script:
    - aws ecs update-service --cluster e-auction --service e-auction-command-api --force-new-deployment --health-check-grace-period-seconds 60
    - aws ecs update-service --cluster e-auction --service e-auction-query-api --force-new-deployment --health-check-grace-period-seconds 60
  only:
  - main

