spring:
  data:
    mongodb:
      authentication-database: admin
      database: e-auction
      port: 27017
      host: user:pass@localhost
      embedded:
        storage:
          repl-set-name: rs0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: e-auction-command-api
  cloud:
    discovery:
       enabled: true
    client:
      hostname: localhost
  rabbitmq:
    password: guest
    port: 5672
    host: localhost
    username: guest

eureka:
  registerWithEureka: true
  fetchRegistry: true
  client:
   serviceUrl:
     defaultZone: http://${eureka.instance.hostname}:9081/eureka/
  instance:
     hostname: localhost

axon:
  amqp:
    exchange: amq.fanout
  eventhandling:
    processors:
      name:
        source: myQueueMessageSource

server:
  port: 9082
  servlet:
    context-path: /command

jwt:
  secret: e-auction
  root-username: user
  root-password: pass
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
        

  