branch-defaults:
  master:
    environment: e-auction-command-api
global:
  application_name: e-auction-command-api
  default_ec2_keyname: e-auction
  default_platform: ECS running on 64bit Amazon Linux 2/3.1.3
  default_region: us-east-1
  profile: eb-cli
  sc: git
